name: Deploy Resume Stack

on:
  push:
    branches:
      - main  # This triggers the code whenever you 'git push' to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # This links to the Environment Secrets you just made
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # -auto-approve is critical because there is no human to type 'yes' in GitHub
        run: terraform apply -auto-approve

      - name: Invalidate CloudFront
        run: |
          DIST_ID=$(terraform output -raw cloudfront_distribution_id)
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"