name: Deploy Resume Stack

on:
  push:
    branches:
      - main # This triggers the code whenever you 'git push' to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # This links to the Environment Secrets you just made

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # -auto-approve is critical because there is no human to type 'yes' in GitHub
        run: terraform apply -auto-approve

      - name: Update Lambda URL in JavaScript
        run: |
          #get the Lambda URL from Terraform output
          LAMBDA_URL=$(terraform output -raw lambda_url)

          # Use 'sed' to replace the placeholder in your script
          # This assumes you have 'const url = "LAMBDA_URL_PLACEHOLDER";' in your script.js

          sed -i "s|LAMBDA_URL_PLACEHOLDER|$LAMBDA_URL|g" website/script.js
          
          # Store the bucket name in the GitHub Environment for the next step
          echo "S3_BUCKET=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Sync S3 Bucket
        run: |
          aws s3 sync ./website s3://${{ env.S3_BUCKET }} --delete 
        # Replace './website' with the folder name where your index.html is located
        #deletes any old files that are no longer in repo
        # TODO : instead of using the secret just pull the bucket name from Terraform output like we did with the cloudfront distribution ID


      # This step captures the ID from main.tf
      - name: Get CloudFront ID
        id: vars
        run: echo "DIST_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      # Now use the variable we just captured instead of the secret
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
